//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WizTodo.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDR_MENU_TRAY                   201
#define IDI_ICON_NEW_BUTTON             205
#define IDI_ICON_LOCK_BUTTON            206
#define IDD_DIALOG_REMIND_EVENT         207
#define IDI_ICON_MENU_BUTTON            207
#define IDB_BITMAP_ALARM                208
#define IDI_ICON_CLOSE_BUTTON           208
#define IDI_ICON_UNLOCK_BUTTON          209
#define IDR_MAINFRAME1                  210
#define IDD_DIALOG_CONFIG_HOTKEY        215
#define IDD_DIALOG_CONFIG_GENERAL       216
#define IDI_ICON_PREV_BUTTON            219
#define IDI_ICON_NEXT_BUTTON            220
#define IDB_BITMAP1                     220
#define IDB_BITMAP_TODO_STATE           220
#define IDR_MENU1                       221
#define IDR_MENU_TODO_ITEM              221
#define IDI_ICON_DOWN_BUTTON            222
#define IDR_MENU_TODO                   222
#define IDI_ICON_DOWN_BUTTON_GRAY       223
#define IDI_ICON_UP_BUTTON              224
#define IDI_ICON_UP_BUTTON_GRAY         225
#define IDD_DIALOG_TODO_LINKS           226
#define IDI_ICON_LOCK_BUTTON1           226
#define IDI_ICON_PIN_DESK_BUTTON        226
#define IDR_MENU_HIDDEN                 228
#define IDS_UNTITLED                    301
#define IDS_UNTITLED_TODOLIST           301
#define IDS_WIZTODO                     302
#define IDS_FAILED_TO_OPEN_DATABASE     303
#define IDS_NEW_TODOLIST                304
#define IDS_RESTORE                     305
#define IDS_MINIMIZE                    306
#define IDS_CANNOT_FIND_WEB_BROWSER     307
#define IDS_NEW_TODOLIST_DESCRIPTION    307
#define IDS_TODOLIST_TITLE_DESCRIPTION  307
#define IDS_OPTIONS                     308
#define IDS_NEW_TODOLIST_TITLE          309
#define IDS_TODAY_TASK                  310
#define IDS_HOTKEY_ERROR                311
#define IDS_NO_CLIPBOARD_DATA_TO_SAVE   312
#define IDS_CHANGE_TODOLIST_TITLE       312
#define IDS_FAILED_TO_REGISTER_HOTKEY   313
#define IDS_TAGS_NAME                   315
#define IDS_FAILED_TO_CREATE_FOLDER     316
#define IDS_COLLECTION_MODE_SAVE_TO_MY_DRAFTS 317
#define IDS_OPEN_WIZEXPLORER            318
#define IDS_REGISTER_HOTKEY_FAILED      319
#define IDS_WIZTODO_IS_RUNNING          320
#define IDS_VIEW_SAVE_RESULT            321
#define IDS_FAILED_TO_SAVE_TODOS        322
#define IDS_ADD_TASK                    323
#define IDS_SELECT_DOCUMENT             324
#define IDS_EDIT_LINK                   325
#define IDS_FAILED_TO_COPY_TODO_ITEM    326
#define IDS_TODO_LIST                   327
#define IDS_COMPACT_MODE                328
#define IDS_NORMAL_MODE                 329
#define IDS_SHOW_TASKS                  333
#define IDS_DELETE_TODO_ITEM            334
#define IDS_OPEN_WIZCALENDAR            335
#define IDC_BUTTON_CLOSE                1001
#define IDC_CHECK_AUTO_RUN              1001
#define IDC_CHECK_AUTO_RUN2             1002
#define IDC_CHECK_AUTO_CREATE_TODAY_TASK_TODO 1002
#define IDC_BUTTON_MENU                 1003
#define IDC_CHECK_SHOW_TASKBAR_BUTTONS  1003
#define IDC_CHECK_MOVE_UNCOMPLETED_TASKS 1004
#define IDC_BUTTON_LOCK                 1005
#define IDC_BUTTON_DONOT_REMIND_ME_AGAIN 1005
#define IDC_BUTTON_COMPLETE             1006
#define IDC_STATIC_BROWSER              1007
#define IDC_HOTKEY_SAVE_WEB_PAGE        1008
#define IDC_HOTKEY_SAVE_CLIPBOARD       1009
#define IDC_EDIT_SYNC_MINUTES           1009
#define IDC_HOTKEY_CREATE_NEW_TODO      1010
#define IDC_SPIN_SYNC_MINUTES           1010
#define IDC_HOTKEY_CREATE_NEW_TODO_LIST 1010
#define IDC_EDIT1                       1011
#define IDC_EDIT_SAVE_TO_DRAFTS         1011
#define IDC_HOTKEY_DISPLAY_TODOS        1011
#define IDC_HOTKEY_DISPLAY_ALL_TODOLISTS 1011
#define IDC_COMBO1                      1016
#define IDC_COMBO_COMPACT_BUTTON        1016
#define IDC_BUTTON_ADD                  1017
#define IDC_COMBO_DOUBLE_CLICK_ACTION   1017
#define IDC_BUTTON_REMOVE               1018
#define IDC_LIST_DOCUMENTS              1019
#define IDC_COMBO_START_OF_DAY          1020
#define IDC_BUTTON_SYNC_OPTIONS         1022
#define IDC_EDIT_CLIP_SCREEN            1161
#define IDC_EDIT_COPY_SELECTION         1164
#define IDC_EDIT_PASTE_CLIPBOARD        1165
#define IDC_BUTTON_RESTORE_DEFAULTS     1166
#define IDC_RADIO_SAVE_TO_MYDRAFTS      1186
#define IDC_RADIO_SAVE_TO_CURRENT_FOLDER 1187
#define IDC_RADIO_PROMPT_LOCATION       1188
#define ID_TRAY_EXIT                    32776
#define ID_TRAY_COLOR                   32781
#define ID_COLOR_BLUE                   32782
#define ID_COLOR_GREEN                  32783
#define ID_COLOR_PINK                   32784
#define ID_COLOR_PURPLE                 32785
#define ID_COLOR_WHITE                  32786
#define ID_COLOR_YELLOW                 32787
#define ID_TRAY_MAKETRANSPARENT         32788
#define ID_MAKETRANSPARENT_OPAQUE       32789
#define ID_MAKETRANSPARENT_30           32790
#define ID_MAKETRANSPARENT_40           32791
#define ID_MAKETRANSPARENT_50           32792
#define ID_MAKETRANSPARENT_60           32793
#define ID_MAKETRANSPARENT_70           32794
#define ID_MAKETRANSPARENT_80           32795
#define ID_MAKETRANSPARENT_90           32796
#define ID_MAKETRANSPARENT_10           32806
#define ID_MAKETRANSPARENT_20           32807
#define ID_TRAY_HELP                    32811
#define ID_HELP_MANUAL                  32812
#define ID_HELP_ABOUT                   32813
#define ID_TRAY_OPTIONS                 32819
#define ID_TODOITEM_0                   32827
#define ID_TODOITEM_25                  32828
#define ID_TODOITEM_50                  32829
#define ID_TODOITEM_75                  32830
#define ID_TODOITEM_100                 32831
#define ID_TODOITEM_DELETE              32832
#define ID_TODOITEM_CREATELINK          32833
#define ID_TODOITEM_CREATELINK32834     32834
#define ID_OPACITY_20                   32835
#define ID_OPACITY_40                   32836
#define ID_OPACITY_60                   32837
#define ID_OPACITY_80                   32838
#define ID_OPACITY_100                  32839
#define ID_TODOITEM_ADDCHILD            32840
#define ID_TODOITEM_NEWTASK             32841
#define ID_TODOITEM_COMPLETE            32847
#define ID_TODOITEM_MOVEUP              32848
#define ID_TODOITEM_MOVEDOWN            32849
#define ID_PRIORITY_NOTURGENTANDNOTIMPORTANT 32850
#define ID_PRIORITY_NORMAL              32851
#define ID_PRIORITY_NOTURGENTBUTIMPORTANT 32852
#define ID_PRIORITY_URGENTBUTNOTIMPORTANT 32853
#define ID_PRIORITY_URGENTANDIMPORTANT  32854
#define ID_TODOITEM_MOVEUP32861         32861
#define ID_TODOITEM_MOVEDOWN32862       32862
#define ID_TODOITEM_DELAYTOTOMORROW     32866
#define ID_TODOITEM_DELAYTO             32867
#define ID_TODOITEM_MOVELEFT            32868
#define ID_TODOITEM_MOVETO              32869
#define ID_TODOITEM_MOVERIGHT           32870
#define ID_TODOITEM_EDIT                32871
#define ID_SMALL_WINDOW_CLOSE           32872
#define ID_TRAY_WIZCALENDAR             32875
#define ID_TRAY_SYNC                    32878
#define ID_TRAY_SHOWALLTODOLISTS        32892
#define ID_TRAY_SHOW_ALL_TODOLISTS      32893
#define ID_TRAY_NEW_TODOLIST            32894
#define ID_HIDDEN_NEWBLANKTODOLIST      32895
#define ID_TODO_CHANGETITLE             32897
#define ID_TODO_LINK_BEGIN              33000
#define ID_TODO_LIST_BEGIN              34000
#define ID_TODO_LIST_END                34020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        229
#define _APS_NEXT_COMMAND_VALUE         32898
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
